### ISSUE TITLE
关于开启border后，min-height: 100vh 属性在ios下的问题

### ISSUE THREAD

**Issue by hooray** [wswmsword/postcss-mobile-forever#40]
开启 border 后，插件默认会给 `#app` 节点增加以下样式

```css
box-shadow: 0 0 0 1px #8888881f;
min-height: 100vh;
height: auto !important;
```

这会导致网页在 ios safari 下浏览时出现滚动条，在 https://www.sabhya.dev/handling-ios-safari-toolbar-for-full-height-web-content 这个链接里有对这一问题进行了详细的描述，并且也提供了解决方案，就是采用 dvh 单位。

我认为生成的代码应该这样会更合理

```css
box-shadow: 0 0 0 1px #8888881f;
min-height: 100vh;
min-height: 100dvh;
height: auto !important;
```

当然如果能处理成这样会更友好

```css
@supports (min-height: 100dvh) {
	#app {
		min-height: 100dvh;
	}
}
```
