### ISSUE TITLE
配置selectorBlackList无效？

### ISSUE THREAD

**Issue by ren2436** [wswmsword/postcss-mobile-forever#56]
`selectorBlackList: ['.ignore', 'keep-px'],`

给元素添加 class ignore，样式中的px依旧会转换为vw，是配置有啥问题么？
目前使用注释的方式是没问题的  /* mobile-ignore-next */

**Comment by wswmsword** [comment]
你好，项目运行之后从浏览器看下元素选择器，选择器的名称有没有被其它插件改变，名称如果在 mobile-forever 检测之前变化，就识别不到你设置的 `['.ignore', 'keep-px']` 了

**Comment by ren2436** [comment]
> 你好，项目运行之后从浏览器开发者工具看下元素选择器，选择器的名称有没有被其它插件改变，名称如果在 mobile-forever 检测之前变化，就识别不到你设置的 `['.ignore', 'keep-px']` 了

![image](https://github.com/user-attachments/assets/64cad5e0-7e36-4f2b-9ce3-1bea641f3769)
我实在是想不到任何办法，用最简单的写法也无法生效

**Comment by wswmsword** [comment]
这个功能是这样的：

```css
.ignore {
  width: 15px;
  margin: 8px;
}
```

```html
<div class="ignore">忽略</div>
```

上面的代码不会转换，下面的代码将会被转换：

```css
.main {
  width: 15px;
  margin: 8px;
}
```

```html
<div class="main ignore">不忽略</div>
```

插件只扫描 CSS 文件，不扫描 HTML 结构，`selectorBlackList` 忽略的是标记选择器名称下的样式，不是在 html 同一 class 下的所有样式。
