### ISSUE TITLE
使用了swiper的页面报错:[vite] Internal server error: [postcss] Cannot read properties of null (reading 'has')

### ISSUE THREAD

**Issue by LUDA0831** [wswmsword/postcss-mobile-forever#59]
### 报错在打包之后的314行,应该是containingBlockWidthDeclsMap这个属性没有判空.
![image](https://github.com/user-attachments/assets/f4267c2f-5e0e-4497-8b85-35957642bbdd)

**Comment by wswmsword** [comment]
感谢，我排除一下

**Comment by wswmsword** [comment]
请问能否提供一下输入输出或者一个能运行的项目包，我本地调试一下。

我看了一下这边逻辑，没找到原因，按照道理走到 314 行的时候应该是已经被赋值了，如果没有值的时候应该走不到第 314 行。这边 `containingBlockWidthDeclsMap` 不能单纯的判空，因为它是需要值来走后面逻辑的。

**Comment by wswmsword** [comment]
4.2.3 已修复，原因是引入了 swiper 的样式，其中包含 `@font-face` At 规则：

```css
@font-face {
  font-family: 'swiper-icons';
  src: url('...');
  font-weight: 400;
  font-style: normal;
}
```

插件假定了 CSS 属性都是在 Rule 之下，没有考虑到 Ar Rule，而原先的 `containingBlockWidthDeclsMap ` 只在 Rule 下面做了初始化，所以遇到 At 规则下有属性的时候可能报错。
