### ISSUE TITLE
小于或者等于1像素的值不转换vw，需要如何配置

### ISSUE THREAD

**Issue by ren2436** [wswmsword/postcss-mobile-forever#7]
如题所示，现在小于1像素也给转换了，导致显示太细，不美观，文档中也没找到如何解决这个问题

想实现 [postcss-px-to-viewport](https://github.com/evrone/postcss-px-to-viewport) 中的配置 minPixelValue 或者 在css 中添加注释 过滤的功能
![image](https://user-images.githubusercontent.com/8308372/233250860-bb62bec1-ac82-4ea8-8644-d2aef75b8f8a.png)

还望能解决下，非常感谢

**Comment by wswmsword** [comment]
这个功能我删掉了，因为小于 1 像素不转换其实是特定场景，也就是在使用边框的时候，`border: 1px solid black;`，其它小于 1px 的情况可能还是需要转换。

目前可以像下面这样，添加注释，不转换 1 像素：

```css
.box {
  border: 1px solid black; /* mobile-ignore */
}
```

上面的是单行注释，也可以添加在属性的上面：

```css
.box {
  /* mobile-ignore-next */
  border: 1px solid black;
}
```

如果注释的意义和你想表达的不一样，也可以自定义注释名称，有两个选项可以设置注释名称，`comment.ignoreLine` 和 `comment. ignoreNext`。
